name: Lint and Test Specific Script

on:
  push:
    branches:
      - main
    paths:
      - '/AcTest/script.py'
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flake8 pytest

      - name: Run lint check on specific script
        run: flake8 AcTest/script.py

      - name: Run tests on specific script
        run: pytest /AcTest/test/script_test.py
